name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    strategy:
      matrix:
        rust:
          - stable
          - 1.70.0
        os:
          - ubuntu-20.04
          - windows-latest
        # The dir feature requires a POSIX system (not Windows).
        include:
          - os: ubuntu-20.04
            features: "--features dir"
          - rust: stable
            extra_components: rustfmt
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ matrix.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: ${{ matrix.extra_components }}
    - name: Test
      run: cargo test ${{ matrix.features }} --all-targets
    - name: Check formatting
      if: matrix.rust == 'stable'
      run: cargo fmt -- --check
    - name: Clippy
      if: matrix.rust == 'stable'
      run: cargo clippy -- -D warnings
